### ISSUE TITLE
Missing info in docs and also adds player?

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/custom_updater#79]
**Version of the custom_component**

Latest
**Describe the bug**
Installed and configured the latest version as per the instructions.

A few issues with new custom updater. 

1. Can’t switch to storage mode until new component loaded otherwise config won’t validate. Should be in the instructions?
2. And cards not in your updater - like the custom-compact-header shit themselves if you change the path - my bad but should be in docs. 
3. Upcoming media card got duplicated one directory level higher instead of staying in it’s configured folder. 
4. I ended up with Thomas Lovens media player as well as the kahlik (?) one
**log**

```
Add your logs here.
```
![image](https://user-images.githubusercontent.com/36390762/52759131-e21b2680-305e-11e9-8b0e-ad65f0855e2d.png)

Note the icon missing from the card title now as well?

Lovelace Config:
```
title: Home
resources:
  - url: /customcards/card-tools.js
    type: js
  - url: /customcards/tracker-card.js
    type: js
  - url: /customcards/custom-lovelace/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /customcards/custom_ui/dark-sky-weather-card.js
    type: module
  - url: /customcards/mini-media-player-bundle.js
    type: module
  - url: /customcards/mini-graph-card-bundle.js
    type: module
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.2
    type: module
  - url: /customcards/fold-entity-row.js
    type: js
  - url: /customcards/button-card.js
    type: module
  - url: /customcards/auto-entities.js
    type: js
```
configuration:
```
# Custom Component Updater
custom_updater:
  show_installable: false
  hide_sensor: false
  mode: storage
  track:
    - components
    - cards
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
```

**Comment by DavidFW1960** [comment]
I saw the icon was removed a few revisions ago if you rename the title... missed that. It can be included in the title though "\U0001F4E3 Custom Card Updates" for instance..

**Comment by ludeeus** [comment]
> Can’t switch to storage mode until new component loaded otherwise config won’t validate. Should be in the instructions?

_[Added](https://github.com/custom-components/custom_updater/wiki/Installation#config-validation)_

> And cards not in your updater - like the custom-compact-header shit themselves if you change the path - my bad but should be in docs.

I can not get it to shit itself, I have that card (working) defined like this:
```
  - type: module
    url: /customcards/compact-custom-header.js
```

> Upcoming media card got duplicated one directory level higher instead of staying in it’s configured folder.

_This was a bug, corrected in 4.0.1_

> * I ended up with Thomas Lovens media player as well as the kahlik (?) one

_This is really strange..., but it may have been the same issue as the one above, try 4.0.1 and see if that helps_

**Comment by DavidFW1960** [comment]
It still adds back player..
![image](https://user-images.githubusercontent.com/36390762/52818912-0ed14b80-30fc-11e9-872a-089ebea97d6f.png)
Mayker has just added back the compact-custom-header to the updater..

**Comment by DavidFW1960** [comment]
I am now getting an error when I change the folder from local to customcards
```
  - url: /customcards/custom-lovelace/compact-custom-header/compact-custom-header.js
    type: module
```
```
Uncaught ReferenceError: LitElement is not defined
    at /customcards/custom-lovelace/compact-custom-header/compact-custom-header-editor.js?v=1.0.0b1:11
```

**Comment by ludeeus** [comment]
> It still adds back player..

_This may be another match issue, will look into it_

> I am now getting an error when I change the folder from local to customcards

_If you try I'm guessing you will get that with /local/ as well, I get that on a system that has not had `custom_updater` installed at any point in time, @maykar has made a change to fix this, if you manually download the newest files it will work_

**Comment by DavidFW1960** [comment]
yep 100% correct. @maykar fixed it now. So it's just the player that I have never used or had. Thanks for looking into this.
I added the store component you showed me on discord as well and it's awesome! Thanks.

**Comment by ludeeus** [comment]
`4.0.2` _should_ take care of the last of your issues.

**Comment by DavidFW1960** [comment]
I see 4.0.1 still (only a minor change from the previous 4.0.1 (REQUIREMENTS = ['pyupdate==0.2.26']) it was pushed 6 hours ago..
I assume you have not pushed 4.0.2 yet?

**Comment by ludeeus** [comment]
That should be it, I may have forgotten to bump a version.

**Comment by DavidFW1960** [comment]
hmm... well I still see player in my list.... should I edit the file in storage to delete that? (stop HA and edit then restart?)

**Comment by ludeeus** [comment]
hold on, Ill check my files

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/52888846-9ad78780-317d-11e9-9db1-f7cecff262e9.png)
This is with your config using the file I pushed ~7h ago.
You should only need to hit "check" to get it working 🤔

**Comment by DavidFW1960** [comment]
I just hit check and it's a Zombie..... still there no change.

I might try the edit....

**Comment by ludeeus** [comment]
The real change happend in pyupdate 0.2.26 https://github.com/ludeeus/pyupdate/commit/3ccf17e8757bf34b0e6097c34aa899fe3264b265 so as long as you have that, it should match correctly :/

**Comment by DavidFW1960** [comment]
OK took a while to find that file and I DO have that one.
Stopping HA, editing the custom_updater.cards to remove player and restarted Home Assistant.
Check again and it's not coming back so fixed!

Thanks for this.

**Comment by pepeEL** [comment]
I use version custom_update 4.0.4 and still not show info about mini-media-player-bundle ... Why ?

**Comment by ludeeus** [comment]
@pepeEL if you did not find the solution in this issue, you have another one.
Therefore you should open another issue.
